## Import library

In [1]:
import pandas as pd

In [2]:
#Load the dataset
df = pd.read_csv(r"C:\Users\LENOVO\Downloads\retail_store_sales.csv")

In [3]:
#show dataset
print(df.head())
df

  Transaction ID Customer ID       Category          Item  Price Per Unit  \
0    TXN_6867343     CUST_09     Patisserie   Item_10_PAT            18.5
1    TXN_3731986     CUST_22  Milk Products  Item_17_MILK            29.0
2    TXN_9303719     CUST_02       Butchers   Item_12_BUT            21.5
3    TXN_9458126     CUST_06      Beverages   Item_16_BEV            27.5
4    TXN_4575373     CUST_05           Food   Item_6_FOOD            12.5

   Quantity  Total Spent  Payment Method Location Transaction Date  \
0      10.0        185.0  Digital Wallet   Online       2024-04-08
1       9.0        261.0  Digital Wallet   Online       2023-07-23
2       2.0         43.0     Credit Card   Online       2022-10-05
3       9.0        247.5     Credit Card   Online       2022-05-07
4       7.0         87.5  Digital Wallet   Online       2022-10-02

  Discount Applied
0             True
1             True
2            False
3              NaN
4            False

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN

In [4]:
# explore the dataset
print("Dataset shape:", df.shape)
print("\nData types:")
print(df.dtypes)

Dataset shape: (12575, 11)

Data types:
Transaction ID       object
Customer ID          object
Category             object
Item                 object
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
Discount Applied     object
dtype: object

In [5]:
# find missing value
print("\nMissing values per column:")
print(df.isnull().sum())

Missing values per column:
Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [6]:
# % of missing valuses
print("\nMissing Values (%)")
print((df.isnull().sum() / len(df) * 100).round(2))

Missing Values (%)
Transaction ID       0.00
Customer ID          0.00
Category             0.00
Item                 9.65
Price Per Unit       4.84
Quantity             4.80
Total Spent          4.80
Payment Method       0.00
Location             0.00
Transaction Date     0.00
Discount Applied    33.39
dtype: float64

In [7]:
# check  duplicate rows
print("Full duplicate rows:", df.duplicated().sum())
df = df.drop_duplicates()

Full duplicate rows: 0

In [8]:
#convert to lowercase and replace spaces with underscore
df.columns = df.columns.str.lower().str.replace(" ", "_")
print("\nColumns after renaming:")
print(df.columns.tolist())

Columns after renaming:
['transaction_id', 'customer_id', 'category', 'item', 'price_per_unit', 'quantity', 'total_spent', 'payment_method', 'location', 'transaction_date', 'discount_applied']

In [9]:
#convert date column to datetime
df["transaction_date"] = pd.to_datetime(df["transaction_date"])
print("\nDate column converted ")
print(df["transaction_date"].dtype)

Date column converted
datetime64[ns]

In [10]:
# Handle missing values
print("\nHandling Missing Values")

# for discount
df["discount_applied"] = df["discount_applied"].fillna(False)
df["discount_applied"] = df["discount_applied"].astype(bool)

# for item
df["item"] = df["item"].fillna("Unknown")

# recalculate Total Spent where possible
mask = df["price_per_unit"].notna() & df["quantity"].notna() & df["total_spent"].isna()
df.loc[mask, "total_spent"] = df.loc[mask, "price_per_unit"] * df.loc[mask, "quantity"]

# drop rows that still have missing important values
df = df.dropna(subset=["price_per_unit", "quantity", "total_spent"]).copy()

print("Shape after handling missing values:", df.shape)

Handling Missing Values
Shape after handling missing values: (11362, 11)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13372\1109316266.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["discount_applied"] = df["discount_applied"].fillna(False)

In [11]:
# drop rows where important numeric values are still missing
df = df.dropna(subset=["price_per_unit", "quantity", "total_spent"])
print("Shape after handling missing values:", df.shape)

Shape after handling missing values: (11362, 11)

In [12]:
# fix data types
df["quantity"] = df["quantity"].astype(int)

print("\nData types after conversion:")
print(df.dtypes)

Data types after conversion:
transaction_id              object
customer_id                 object
category                    object
item                        object
price_per_unit             float64
quantity                     int64
total_spent                float64
payment_method              object
location                    object
transaction_date    datetime64[ns]
discount_applied              bool
dtype: object

In [13]:
#standardize text values
df["category"] = df["category"].str.strip().str.title()
df["item"] = df["item"].str.strip()
df["payment_method"] = df["payment_method"].str.strip().str.title()
df["location"] = df["location"].str.strip().str.title()

print("\nUnique values after standardization:")
print("Categories:", df["category"].unique())
print("Payment Methods:", df["payment_method"].unique())
print("Locations:", df["location"].unique())

Unique values after standardization:
Categories: ['Patisserie' 'Milk Products' 'Butchers' 'Beverages' 'Food' 'Furniture'
 'Electric Household Essentials' 'Computers And Electric Accessories']
Payment Methods: ['Digital Wallet' 'Credit Card' 'Cash']
Locations: ['Online' 'In-Store']

In [14]:
#Final check
print("\nFINAL CLEANED DATASET SUMMARY")
print("Final shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())
print("\nData types:")
print(df.dtypes)
print("\nMissing values left:")
print(df.isnull().sum())
print("\nFirst 5 rows of cleaned data:")
print(df.head())
df

FINAL CLEANED DATASET SUMMARY
Final shape: (11362, 11)

Columns:
['transaction_id', 'customer_id', 'category', 'item', 'price_per_unit', 'quantity', 'total_spent', 'payment_method', 'location', 'transaction_date', 'discount_applied']

Data types:
transaction_id              object
customer_id                 object
category                    object
item                        object
price_per_unit             float64
quantity                     int64
total_spent                float64
payment_method              object
location                    object
transaction_date    datetime64[ns]
discount_applied              bool
dtype: object

Missing values left:
transaction_id      0
customer_id         0
category            0
item                0
price_per_unit      0
quantity            0
total_spent         0
payment_method      0
location            0
transaction_date    0
discount_applied    0
dtype: int64

First 5 rows of cleaned data:
  transaction_id customer_id       category          item  price_per_unit  \
0    TXN_6867343     CUST_09     Patisserie   Item_10_PAT            18.5
1    TXN_3731986     CUST_22  Milk Products  Item_17_MILK            29.0
2    TXN_9303719     CUST_02       Butchers   Item_12_BUT            21.5
3    TXN_9458126     CUST_06      Beverages   Item_16_BEV            27.5
4    TXN_4575373     CUST_05           Food   Item_6_FOOD            12.5

   quantity  total_spent  payment_method location transaction_date  \
0        10        185.0  Digital Wallet   Online       2024-04-08
1         9        261.0  Digital Wallet   Online       2023-07-23
2         2         43.0     Credit Card   Online       2022-10-05
3         9        247.5     Credit Card   Online       2022-05-07
4         7         87.5  Digital Wallet   Online       2022-10-02

   discount_applied
0              True
1              True
2             False
3             False
4             False

,transaction_id,customer_id,category,item,price_per_unit,quantity,total_spent,payment_method,location,transaction_date,discount_applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9,247.5,Credit Card,Online,2022-05-07,False
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7,87.5,Digital Wallet,Online,2022-10-02,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4,152.0,Credit Card,In-Store,2023-09-03,False
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10,140.0,Cash,Online,2024-08-24,False
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3,51.0,Cash,Online,2022-08-06,False

In [15]:
#saved the cleaned dataset
df.to_csv("retail_store_sales_cleaned.csv", index=False)
print("\nCleaned dataset saved as: retail_store_sales_cleaned.csv")

Cleaned dataset saved as: retail_store_sales_cleaned.csv